core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='MovieList'),
    path('movies/top/', views.TopMovies.as_view(), name='TopMovies'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='MovieDetail'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload/', views.MovieImageUpload.as_view(), name='MovieImageUpload'),
]

mymdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
] + MEDIA_FILE_PATHS

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <title>
        {% block title %}MyMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <a class="navbar-brand">MyMDB</a> <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a><a
                class="nav-link" href="{% url 'core:TopMovies' %}">Top 10 Movies</a>
        </nav>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>